// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eaudit.data.Data;

namespace eaudit.data.Migrations
{
    [DbContext(typeof(EauditDbContext))]
    [Migration("20220707000524_esqueci-dos-mapeamentos")]
    partial class esquecidosmapeamentos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("eaudit.data.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("Cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Cpf");

                    b.HasIndex("Nome");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("eaudit.data.Model.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FilmesId");

                    b.Property<int>("ClassificacaoIndicativa")
                        .HasColumnType("int")
                        .HasColumnName("ClassificacaoIndicativa");

                    b.Property<int>("Lancamento")
                        .HasColumnType("int")
                        .HasColumnName("Lancamento");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("Lancamento");

                    b.HasIndex("Titulo");

                    b.ToTable("filmes");
                });

            modelBuilder.Entity("eaudit.data.Model.Locacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocacaoId");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Cliente");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataDevolucao");

                    b.Property<DateTime>("DataLocacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataLocacao");

                    b.Property<int>("FilmeId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Filme");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FilmeId");

                    b.ToTable("locacao");
                });

            modelBuilder.Entity("eaudit.data.Model.Locacao", b =>
                {
                    b.HasOne("eaudit.data.Model.Cliente", "Cliente")
                        .WithMany("Locacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eaudit.data.Model.Filme", "Filme")
                        .WithMany("Locacoes")
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("eaudit.data.Model.Cliente", b =>
                {
                    b.Navigation("Locacoes");
                });

            modelBuilder.Entity("eaudit.data.Model.Filme", b =>
                {
                    b.Navigation("Locacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
